/**
 * Generates public/sitemap.xml from the site's own data.
 *
 * The notes archive is ~60 PDFs and grows; hand-maintaining the sitemap would
 * guarantee it drifts. Reading noteTracks means a new document is indexable as
 * soon as it is added to src/data/notes.js — no second place to remember.
 *
 * Runs automatically via the `prebuild` npm script.
 */
import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { noteTracks } from '../src/data/notes.js';
import { resumeUrl, siteUrl } from '../src/data/site.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const origin = siteUrl.replace(/\/$/, '');

/** `lastmod` must be a real date, so take it from the file on disk. */
function modifiedAt(publicPath) {
  try {
    return statSync(join(root, 'public', publicPath)).mtime.toISOString().slice(0, 10);
  } catch {
    return null; // File not published yet — omit lastmod rather than invent one.
  }
}

const today = new Date().toISOString().slice(0, 10);

const pages = [
  { loc: '/', changefreq: 'monthly', priority: '1.0', lastmod: today },
  { loc: '/notes/', changefreq: 'weekly', priority: '0.8', lastmod: today },
  {
    loc: resumeUrl,
    changefreq: 'monthly',
    priority: '0.6',
    lastmod: modifiedAt(resumeUrl),
  },
];

// Every published note PDF. Google indexes PDFs and these are the only
// long-form original content on the site, so they are worth surfacing.
for (const track of noteTracks) {
  if (track.status !== 'published' || !track.basePath) continue;

  for (const module of track.modules) {
    for (const doc of module.docs) {
      const path = `${track.basePath}/${doc.file}`;
      pages.push({
        loc: path,
        changefreq: 'yearly',
        priority: '0.5',
        lastmod: modifiedAt(path),
      });
    }
  }
}

const body = pages
  .map(({ loc, changefreq, priority, lastmod }) =>
    [
      '  <url>',
      `    <loc>${origin}${encodeURI(loc)}</loc>`,
      lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      '  </url>',
    ]
      .filter(Boolean)
      .join('\n'),
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

mkdirSync(join(root, 'public'), { recursive: true });
writeFileSync(join(root, 'public', 'sitemap.xml'), xml);

console.log(`sitemap.xml — ${pages.length} URLs`);
